nyc = City.create(name: 'New York City')
madrid = City.create(name: 'Madrid')
rincon = City.create(name: 'Rincón')
paris = City.create(name: 'Paris')


Restaurant.create(name: "Misti's", nationality: "Peruvian", rating: 10, city: nyc)
Restaurant.create(name: "Afridi Halal Food Cart", nationality: "Halal", rating: 10, city: nyc)
Restaurant.create(name: "Sandfords Astoria", nationality: "American", rating: 8, city: nyc)
Restaurant.create(name: "Vi Ale Gelateria", nationality: "Italian", rating: 7, city: nyc)
Restaurant.create(name: "Lazy Lobster", nationality: "American", rating: 7, city: nyc)
Restaurant.create(name: "Laurel Diner", nationality: "American", rating: 9, city: nyc)
Restaurant.create(name: "Tony's Beechhurst Deli", nationality: "Italian", rating: 10, city: nyc)
Restaurant.create(name: "Bean & Bean", nationality: "Japanese", rating: 8, city: nyc)
Restaurant.create(name: "Saint Honore Pastry Shop", nationality: "French", rating: 8, city: nyc)
Restaurant.create(name: "Schmear Bakery & Market", nationality: "Jewish-Kosher", rating: 7, city: nyc)
Restaurant.create(name: "Asian 59", nationality: "Chinese", rating: 9, city: nyc)
Restaurant.create(name: "Yummy Gyro", nationality: "Greek", rating: 10, city: nyc)
Restaurant.create(name: "Maman", nationality: "French", rating: 8, city: nyc)
Restaurant.create(name: "Chifa Restaurant", nationality: "Peruvian-Japanese", rating: 2, city: nyc)

Restaurant.create(name: "Malvy's Shakes", nationality: "Spanish", rating: 8, city: madrid)
Restaurant.create(name: "Pizzart Fuencarral", nationality: "Italian", rating: 9, city: madrid)
Restaurant.create(name: "Chocolatería San Ginés", nationality: "Spanish", rating: 10, city: madrid)
Restaurant.create(name: "Pituca Madrid", nationality: "Peruvian", rating: 7, city: madrid)
Restaurant.create(name: "Cherry Pecas", nationality: "Mexican", rating: 7, city: madrid)
Restaurant.create(name: "The Irish Temple", nationality: "Irish", rating: 10, city: madrid)

Restaurant.create(name: "Ricomimi Bakery", nationality: "Puerto Rican", rating: 9 , city: rincon)
Restaurant.create(name: "La Taqueria Wepa", nationality: "Puerto Rican", rating: 6 , city: rincon)
Restaurant.create(name: "Gastropark @ 115", nationality: "Puerto Rican", rating: 9 , city: rincon)
Restaurant.create(name: "Mangia Mi", nationality: "Italian", rating: 7, city: rincon)
Restaurant.create(name: "Rincón Smoke Shack", nationality: "American", rating: 9 , city: rincon)
Restaurant.create(name: "estela Restaurant", nationality: "Vegan-American", rating: 8, city: rincon)
Restaurant.create(name: "Parrilleria Vacas Gauchas", nationality: "American", rating: 9 , city: rincon)


Restaurant.create(name: "Le Loulou", nationality: "French", rating: 9, city: paris)
Restaurant.create(name: "Le 43 Roof Top", nationality: "French", rating: 7, city: paris)
Restaurant.create(name: "Ladurée", nationality: "French", rating: 9, city: paris)
Restaurant.create(name: "Kodawari Ramen", nationality: "Japanese", rating: 9, city: paris)
Restaurant.create(name: "Presto Fresco", nationality: "Italian", rating: 9, city: paris)
Restaurant.create(name: "Bistrot Kinzo", nationality: "Japanese", rating: 8, city: paris)
Restaurant.create(name: "Domenico's", nationality: "Italian", rating: 8, city: paris)
Restaurant.create(name: "XV Burger", nationality: "American", rating: 9, city: paris)
